name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Pipeline started"

    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v4

    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: |
        echo "Configuring CMake"
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        echo "Building project"
        cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      run: |
        echo "Running tests"
        cd build
        ctest --output-on-failure -C ${{env.BUILD_TYPE}}

    - run: echo "Pipeline finished"
